name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: cd app && npm install

      - name: Run tests
        run: cd app && npm test
