name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: ls && cd app/src && npm install

  Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        run: cd app && npm test
