name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd app
          npm install
      - name: Run tests
        run: |
          cd app
          npm test

  Tests:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd app
          npm install
      - name: Run tests
        run: |
          cd app
          npm test

  Publish:
    needs: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd app
          npm install
      - name: Zip files
        run: |
          zip -r lambda.zip app/
          mv lambda.zip ./infra/lambda.zip
      - name: Terraform init
        run: |
          cd infra
          terraform init
      - name: Terraform plan
        run: |
          cd infra
          terraform init
          terraform plan -out=tfplan -refresh=true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Terraform apply
        run: |
          cd infra
          terraform plan -out=tfplan -refresh=true
          terraform apply -auto-approve "tfplan"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
