name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TF_ACTION_WORKING_DIR: "infra"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd app
          npm install
      - name: Run tests
        run: |
          cd app
          npm test

  Tests:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd app
          npm install
      - name: Run tests
        run: |
          cd app
          npm test

  Publish:
    needs: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd app
          npm install
      - name: Zip files
        run: |
          zip -r lambda.zip app/
          mv lambda.zip ./infra/lambda.zip
      - name: Terraform init
        run: |
          cd infra
          terraform init
      - name: Terraform plan
        run: |
          cd infra
          terraform plan
      - name: Terraform apply
        run: |
          cd infra
          terraform apply -auto-approve
